[package]
name = "slam-receiver"
version = "0.1.0"
edition = "2024"
default-run = "slam-receiver"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
ctrlc = "3.5.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["raw_value"] }
zmq = "0.10.0"
